name = "safepeek"
main = "src/index.ts"
compatibility_date = "2024-01-29"
compatibility_flags = ["nodejs_compat"]

vars = { NODE_ENV = "production" }

[[kv_namespaces]]
binding = "CONFIG"
id = "016a364fc2854b758ee01504fdf01b72"

[[kv_namespaces]]
binding = "USER_CACHE"
id = "83debe59d30c4b92ae726ef5fcd39842"

[env.development]

[placement]
mode = "smart"
